careon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.OrderListView.as_view(), name='list'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='detail'),
    path('add/', views.OrderCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', views.OrderDeleteView.as_view(), name='delete'),

    path('product/add/<int:pk>/', views.OrderProductCreateView.as_view(), name='product-create'),
    path('product/edit/<int:pk>/', views.OrderProductUpdateView.as_view(), name='product-update'),
    path('product/delete/<int:pk>/', views.OrderProductDeleteView.as_view(), name='product-delete'),

    path('product/new/<int:pk>/', views.ProductAddView.as_view(), name='product-new'),
]

core/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('add/', views.ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', views.ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('result/', views.CalculateView.as_view(), name='result'),
    path('products/', include("core.product.urls")),
    path('order/', include("core.order.urls")),
]

core/models.py
from django.db import models

class Products(models.Model):
    ATTACHED=1
    NOT_ATTACHED=0
    REINFORCEMENTS=(
        (ATTACHED, 'Attached'),
        (NOT_ATTACHED, 'Not Attached')
    )
    NORMAL_FOLDING=0
    AMRITHA_FOLDING=1
    FOLDS=(
        (NORMAL_FOLDING, 'Normal'),
        (AMRITHA_FOLDING, 'Amritha'),
    )
    TIE_2 = 1
    TIE_4X6 = 2
    TIES_CHOICES=(
        (TIE_2, "2"),
        (TIE_4X6, "4/6"),
    )
    name = models.CharField(max_length=100)
    reinforcement = models.PositiveSmallIntegerField(choices=REINFORCEMENTS)
    folding = models.PositiveSmallIntegerField(choices=FOLDS)
    ties = models.PositiveSmallIntegerField(choices=TIES_CHOICES)

    default = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Orders(models.Model):
    name = models.CharField(max_length=100)

    def _get_products(self, **kwargs):
        return OrderProducts.objects.filter(order=self, **kwargs)

    def products(self):
        return self._get_products()

    def total_demand(self):
        return self._get_products().aggregate(models.Sum('demand'))['demand__sum'] or 0


class OrderProducts(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    demand = models.PositiveIntegerField()

core/forms.py
from django import forms

from core.models import Products


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        exclude = ("default",)

core/order/forms.py
from django import forms

from core.models import Orders, OrderProducts


class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = "__all__"


class OrderProductForm(forms.ModelForm):
    class Meta:
        model = OrderProducts
        exclude = ("order",)

core/product/forms.py
from django import forms

from core.models import Products


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        exclude = ("default",)


class SelectProductForm(forms.Form):
    Product = forms.ModelChoiceField(queryset=Products.objects.all())

core/order/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from core.base_views import BaseDeleteView
from core.models import Orders, OrderProducts, Products
from core.order.forms import OrderForm, OrderProductForm
from core.product.views import ProductCreateView


class OrderListView(ListView):
    model = Orders
    template_name = 'order/list.html'
    context_object_name = 'orders'


class OrderDetailView(DetailView):
    model = Orders
    template_name = 'order/detail.html'
    context_object_name = 'order'


class OrderCreateView(CreateView):
    model = Orders
    form_class = OrderForm
    template_name = 'order/create.html'

    def get_success_url(self):
        return reverse_lazy('order:detail', kwargs={'pk': self.object.pk})


class OrderDeleteView(BaseDeleteView):
    model = Orders
    success_url = reverse_lazy("order:list")
    success_message = "order has been deleted"


class OrderProductCreateView(CreateView):
    model = OrderProducts
    form_class = OrderProductForm
    template_name = 'order/select.html'

    @staticmethod
    def get_products():
        products = Products.objects.all()
        products_data = {
            str(p.id): {
                'name': p.name,
                'reinforcement': p.get_reinforcement_display(),
                'folding': p.get_folding_display(),
                'ties': p.get_ties_display(),
            } for p in products
        }
        return products_data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "pk": self.kwargs["pk"],
            "products": Products.objects.all(),
            "products_json": self.get_products(),
        })
        return context

    def get_success_url(self):
        return reverse_lazy('order:detail', kwargs={'pk': self.object.order.pk})

    def form_valid(self, form):
        order = Orders.objects.get(pk=self.kwargs['pk'])
        form.instance.order = order
        return super().form_valid(form)


class OrderProductUpdateView(UpdateView):
    model = OrderProducts
    form_class = OrderProductForm
    template_name = 'order/change.html'

    def get_success_url(self):
        return reverse_lazy('order:detail', kwargs={'pk': self.object.order.pk})


class OrderProductDeleteView(BaseDeleteView):
    model = OrderProducts
    success_message = "product has been deleted"

    def get_success_url(self):
        return reverse_lazy('order:detail', kwargs={'pk': self.object.order.pk})


class ProductAddView(ProductCreateView):
    template_name = "order/change.html"

    def get_success_url(self):
        return reverse_lazy('order:product-create', kwargs={'pk': self.kwargs['pk']})

core/product/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from core.models import Products
from .forms import ProductForm
from ..base_views import BaseDeleteView


class ProductListView(ListView):
    queryset = Products.objects.filter(default=True)
    template_name = 'products/list.html'
    context_object_name = 'products'


class ProductDetailView(DetailView):
    model = Products
    template_name = 'products/detail.html'
    context_object_name = 'product'


class ProductCreateView(CreateView):
    model = Products
    form_class = ProductForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('product:list')


class ProductUpdateView(UpdateView):
    model = Products
    form_class = ProductForm
    template_name = 'products/update.html'
    success_url = reverse_lazy('product:list')


class ProductDeleteView(BaseDeleteView):
    model = Products
    success_url = reverse_lazy('product:list')
    success_message = "product successfully deleted"

core/views.py
from django.urls import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from core.models import Products


class IndexView(RedirectView):
    permanent = True
    url = reverse_lazy('order:list')

    @staticmethod
    def create_products_if_not_exist():
        products = [
            {"name": "Product A", "reinforcement": Products.ATTACHED, "folding": Products.AMRITHA_FOLDING,
             "ties": Products.TIE_2},
            {"name": "Product B", "reinforcement": Products.ATTACHED, "folding": Products.NORMAL_FOLDING,
             "ties": Products.TIE_2},
            {"name": "Product C", "reinforcement": Products.ATTACHED, "folding": Products.AMRITHA_FOLDING,
             "ties": Products.TIE_4X6},
            {"name": "Product D", "reinforcement": Products.ATTACHED, "folding": Products.NORMAL_FOLDING,
             "ties": Products.TIE_4X6},
            {"name": "Product E", "reinforcement": Products.NOT_ATTACHED, "folding": Products.AMRITHA_FOLDING,
             "ties": Products.TIE_2},
            {"name": "Product F", "reinforcement": Products.NOT_ATTACHED, "folding": Products.NORMAL_FOLDING,
             "ties": Products.TIE_2},
            {"name": "Product G", "reinforcement": Products.NOT_ATTACHED, "folding": Products.AMRITHA_FOLDING,
             "ties": Products.TIE_4X6},
            {"name": "Product H", "reinforcement": Products.NOT_ATTACHED, "folding": Products.NORMAL_FOLDING,
             "ties": Products.TIE_4X6},
        ]
        for product in products:
            if not Products.objects.filter(name=product["name"]).exists():
                Products.objects.create(**product)

    def get(self, request, *args, **kwargs):
        self.create_products_if_not_exist()
        return super().get(request, *args, **kwargs)


class CalculateView(TemplateView):
    template_name = "result.html"

core/templates/order/change.html
{% extends "includes/base.html" %}

{% block navbar_title %}
    Orders / Product / Edit
{% endblock %}

{% block content %}
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10 col-xl-8">
                <div class="card border-0 shadow-sm rounded-3">
                    <div class="card-body p-4">
                        {% include "includes/form.html" with form=form submit_label="Save" show_secondary_btn=True %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/order/create.html
{% extends "includes/base.html" %}

{% block navbar_title %}
    Orders / Add
{% endblock %}

{% block content %}
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10 col-xl-8">
                <div class="card border-0 shadow-sm rounded-3">
                    <div class="card-body p-4">
                        {% include "includes/form.html" with form=form submit_label="Submit" show_secondary_btn=True %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/order/select.html
{% extends "includes/base.html" %}

{% block navbar_title %}
    Orders / Product / Add
{% endblock %}

{% block extra_css %}
    <style>
        .product-select-wrapper {
            display: flex;
            gap: 10px;
            align-items: center;
        }

        .product-select-wrapper select {
            flex: 1;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 6px;
            font-size: 14px;
        }

        .info-btn {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            border: 2px solid #007bff;
            background: #007bff;
            color: white;
            font-weight: bold;
            cursor: pointer;
            transition: all 0.3s;
        }

        .info-btn:disabled {
            background: #e9ecef;
            border-color: #dee2e6;
            color: #6c757d;
            cursor: not-allowed;
        }

        .info-btn:not(:disabled):hover {
            background: #0056b3;
            border-color: #0056b3;
            transform: scale(1.1);
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: 500;
            color: #333;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 6px;
            font-size: 14px;
        }

        .submit-btn {
            width: 100%;
            padding: 12px;
            background: #28a745;
            color: white;
            border: none;
            border-radius: 6px;
            font-size: 16px;
            font-weight: 500;
            cursor: pointer;
            transition: background 0.3s;
        }

        .submit-btn:hover {
            background: #218838;
        }

        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            z-index: 1000;
            opacity: 0;
            transition: opacity 0.3s;
        }

        .modal.active {
            display: flex;
            align-items: center;
            justify-content: center;
            opacity: 1;
        }

        .modal-content {
            background: white;
            border-radius: 12px;
            max-width: 500px;
            width: 90%;
            max-height: 80vh;
            overflow-y: auto;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
            animation: slideDown 0.3s;
        }

        @keyframes slideDown {
            from {
                transform: translateY(-50px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .modal-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            border-bottom: 1px solid #eee;
        }

        .modal-header h3 {
            margin: 0;
            font-size: 20px;
            color: #333;
        }

        .close-btn {
            background: none;
            border: none;
            font-size: 28px;
            color: #999;
            cursor: pointer;
            line-height: 1;
            transition: color 0.3s;
        }

        .close-btn:hover {
            color: #333;
        }

        .product-details {
            padding: 20px;
        }

        .product-image {
            width: 100%;
            max-height: 250px;
            object-fit: cover;
            border-radius: 8px;
            margin-bottom: 15px;
        }

        .product-details p {
            margin: 10px 0;
            font-size: 14px;
            color: #555;
        }

        .product-details strong {
            color: #333;
        }

        .card {
            padding: 30px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10 col-xl-8">
                <div class="card border-0 shadow-sm rounded-3">
                    <form method="post" class="needs-validation" id="orderProductForm">
                        {% csrf_token %}

                        {# General errors #}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger alert-dismissible fade show mb-3">
                                <strong>Please correct the following errors:</strong>
                                {% for e in form.non_field_errors %}
                                    <div class="mt-1">{{ e }}</div>
                                {% endfor %}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <label for="id_product">Product *</label>
                            <div class="product-select-wrapper">
                                <select name="product" id="id_product" required>
                                    <option value="">Select a product</option>
                                    {% for product in products %}
                                        <option value="{{ product.id }}"
                                                {% if form.product.value == product.id %}selected{% endif %}>
                                            {{ product.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                                <button type="button" class="info-btn" id="infoBtn" disabled
                                        title="Select a product first">i
                                </button>
                            </div>
                            {% if form.product.errors %}
                                <div class="text-danger mt-1">
                                    {% for error in form.product.errors %}
                                        <small>{{ error }}</small>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="id_demand">Quantity *</label>
                            <input type="number" name="demand" id="id_demand" min="1"
                                   value="{{ form.demand.value|default:'' }}" required>
                            {% if form.demand.errors %}
                                <div class="text-danger mt-1">
                                    {% for error in form.demand.errors %}
                                        <small>{{ error }}</small>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="d-flex justify-content-end gap-2">
                            <a href="#" onclick="window.history.back()"
                               class="btn btn-outline-secondary">
                                Cancel
                            </a>
                            <a href="{% url 'order:product-new' pk %}" onclick="window.history.back()"
                               class="btn btn-outline-secondary">
                                Add New Product
                            </a>
                            <button type="submit" class="btn btn-dark px-4" id="submit-btn">
                                <span class="submit-text">Add to Order</span>
                                <span class="spinner-border spinner-border-sm ms-2 d-none"></span>
                            </button>
                        </div>
                    </form>

                    <!-- Modal -->
                    <div id="productModal" class="modal">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3>Product Details</h3>
                                <button type="button" class="close-btn" id="closeModal">&times;</button>
                            </div>
                            <div id="modalBody" class="product-details">
                                <!-- Product details will be inserted here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    {{ products_json|json_script:"product-data" }}
    <script>
        // Parse product data from Django context
        const productDataElement = document.getElementById('product-data');
        const productData = productDataElement ? JSON.parse(productDataElement.textContent) : {};

        const productSelect = document.getElementById('id_product');
        const infoBtn = document.getElementById('infoBtn');
        const modal = document.getElementById('productModal');
        const closeModal = document.getElementById('closeModal');
        const modalBody = document.getElementById('modalBody');

        // Enable/disable info button based on selection
        productSelect.addEventListener('change', function () {
            infoBtn.disabled = !this.value;
            infoBtn.title = this.value ? 'View product details' : 'Select a product first';
        });

        // Show modal with product details
        infoBtn.addEventListener('click', function () {
            const selectedProductId = productSelect.value;
            if (selectedProductId && productData[selectedProductId]) {
                const product = productData[selectedProductId];

                let imageHtml = '';
                if (product.image) {
                    imageHtml = `<img src="${product.image}" alt="${product.name}" class="product-image" onerror="this.style.display='none'">`;
                }

                modalBody.innerHTML = `
                    ${imageHtml}
                    <p><strong>Name:</strong> ${product.name}</p>
                    ${product.reinforcement ? `<p><strong>Reinforcement:</strong> ${product.reinforcement}</p>` : ''}
                    ${product.folding ? `<p><strong>Folding:</strong> ${product.folding}</p>` : ''}
                    ${product.ties !== undefined ? `<p><strong>Ties:</strong> ${product.ties}</p>` : ''}
                `;

                modal.classList.add('active');
            }
        });

        // Close modal
        closeModal.addEventListener('click', function () {
            modal.classList.remove('active');
        });

        // Close modal when clicking outside
        modal.addEventListener('click', function (e) {
            if (e.target === modal) {
                modal.classList.remove('active');
            }
        });

        // Close modal with Escape key
        document.addEventListener('keydown', function (e) {
            if (e.key === 'Escape' && modal.classList.contains('active')) {
                modal.classList.remove('active');
            }
        });

        // Handle form validation on submit
        const form = document.getElementById('orderProductForm');
        form.addEventListener('submit', function (e) {
            if (!form.checkValidity()) {
                e.preventDefault();
                e.stopPropagation();
            }
            form.classList.add('was-validated');
        });
    </script>
{% endblock %}

core/templates/order/update.html
{% extends "includes/base.html" %}

{% block navbar_title %}
    Orders / Edit
{% endblock %}

{% block content %}
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10 col-xl-8">
                <div class="card border-0 shadow-sm rounded-3">
                    <div class="card-body p-4">
                        {% include "includes/form.html" with form=form submit_label="Save" show_secondary_btn=True %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}